version: '3.1'

services:
  postgres:
    image: postgres:14.5
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_DB=boardroom
      - POSTGRES_USER=boardroom
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped
